config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :places do
    resources :reviews, only: [:new, :create]
  end
  post "reviews", to: "reviews#create"

  devise_for :users
  root to: "pages#home"

  #this sends the api placename to the controller
  post 'pages/receive_place_name', to: 'pages#receive_place_name'

  #this sends the api placename to the controller
  get 'pages/render_reviews', to: 'pages#render_reviews'
  get 'pages/render_tags', to: 'pages#render_tags'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "end_reviews/:place_ids", to: "reviews#end_reviews", as: :end_reviews

  patch "places/:id", to: "places#update"

  post "/places/end_reviews", to: "places#end_reviews"

  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
end

app/views/javier/_buttons.html.erb
<div class="d-flex justify-content-around">
  <button href="#" class="icon-button rounded-pill text animated-button px-1 focus" id="suggested-btn" style="border-radius: 20px;">🧐 Latest</button>
  <button href="#" class="icon-button rounded-pill text animated-button px-1 focus" id="mylist-btn" style="border-radius: 20px;">📝 My Reviews</button>
</div>
<%# <div class="d-flex justify-content-between p-2" id="main-buttons">
  <button href="#" class="btn btn-primary shadow-lg flex-grow-1 mx-1" id="recent-btn" style="border-radius: 20px;">Most Recent</button>
  <button href="#" class="btn btn-light shadow-sm flex-grow-1 mx-1" id="popular-btn" style="border-radius: 20px;">Most Popular</button>
  <button href="#" class="btn btn-light shadow-sm flex-grow-1 mx-1" id="create-btn" style="border-radius: 20px;">Create New</button>
</div> %>

app/views/javier/_create_content.html.erb
<div id="create-content" class="content-section d-none">
  <%= simple_form_for @review do |f| %>
    <div class="form-group">
      <%= f.input :photos, as: :file, label: "Upload Photo" %>
    </div>

    <div class="form-group">
      <%= f.input :comment, label: "Comment", input_html: { maxlength: 50 } %>
    </div>

    <div class="form-group">
      <%= f.input :rating, collection: [1, 2, 3, 4, 5], label: "Rating" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/javier/_mylist_content.html.erb
<div id="mylist-content" class="content-section d-none mt-3">
  <div id="review-places-list" class="list-group">
    <% @reviews.where(user: current_user).order(created_at: :desc).each do |review| %>
      <div class="review-place list-group-item p-3 border-0 shadow-sm mb-3" style="border-radius: 10px; background-color: #fff;">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <%= cl_image_tag review.user.photo.key, class: "avatar me-2 rounded-circle" %>
            <h6 class="m-0"><strong><%= review.user.username %></strong></h6>
          </div>
          <div class="d-flex align-items-center">
            <% if review.user == current_user %>
              <%= link_to delete_review_path(review), data: { turbo_method: :delete }, class: "btn btn-danger btn-aya btn-md btn-block me-2" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
            <button class="btn btn-light btn-md btn-block"><i class="fas fa-thumbs-up"></i></button>
          </div>
        </div>
        <div class="d-flex w-100 justify-content-between my-3">
          <div class="w-100 star-rating" style="font-size: 20px;">
            <strong id="<%= review.place.google_id %>" data-action="click->home-map#javi"><%= review.place.name %></strong>
            <div style="min-width: fit-content; max-width: 100px;">
              <% r_rating = review.rating %>
              <% r_rating.times do %>
                <i class="fa-solid fa-baby-carriage text-warning"></i>
              <% end %>
            </div>
          </div>
        </div>
        <% if review.photos.any? %>
          <%= cl_image_tag review.photos[0].key, class: "place-image mb-3 w-100 rounded" %>
        <% end %> <!-- Only show image if there are photos -->
        <p class="mb-1 text-muted"><%= review.comment %></p>
        <p class="text-muted mt-3" style="font-size: 12px;"><%= review.created_at.strftime("%H:%M %B %d, %Y") %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/javier/_suggested_content.html.erb
<div id="suggested-content" class="content-section mt-3">
  <div id="review-places-list" class="list-group">
    <% @reviews.order(created_at: :desc).each do |review| %>
      <div class="review-place list-group-item p-3 border-0 shadow-sm mb-3" style="border-radius: 10px; background-color: #fff;">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <%= cl_image_tag review.user.photo.key, class: "avatar me-2 rounded-circle" %>
            <h6 class="m-0"><strong><%= review.user.username %></strong></h6>
          </div>
          <div class="d-flex align-items-center">
            <% if review.user == current_user %>
              <%= link_to delete_review_path(review), data: { turbo_method: :delete }, class: "btn btn-danger btn-aya btn-md btn-block me-2" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
            <button class="btn btn-light btn-md btn-block"><i class="fas fa-thumbs-up"></i></button>
          </div>
        </div>
        <div class="d-flex w-100 justify-content-between my-3">
          <div class="w-100 star-rating" style="font-size: 20px;">
            <strong id="<%= review.place.google_id %>" data-action="click->home-map#javi"><%= review.place.name %></strong>
            <div style="min-width: fit-content; max-width: 100px;">
              <% r_rating = review.rating %>
              <% r_rating.times do %>
                <i class="fa-solid fa-baby-carriage text-warning"></i>
              <% end %>
            </div>
          </div>
        </div>
        <% if review.photos.any? %>
          <%= cl_image_tag review.photos[0].key, class: "place-image mb-3 w-100 rounded" %>
        <% end %> <!-- Only show image if there are photos -->
        <p class="mb-1 text-muted"><%= review.comment %></p>
        <p class="text-muted mt-3" style="font-size: 12px;"><%= review.created_at.strftime("%H:%M %B %d, %Y") %></p>
      </div>
    <% end %>
  </div>
</div>