config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :places do
    resources :reviews, only: [:new, :create]
  end
  post "reviews", to: "reviews#create"

  devise_for :users
  root to: "pages#home"

  #this sends the api placename to the controller
  post 'pages/receive_place_name', to: 'pages#receive_place_name'

  #this sends the api placename to the controller
  get 'pages/render_reviews', to: 'pages#render_reviews'
  get 'pages/render_tags', to: 'pages#render_tags'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "end_reviews/:place_ids", to: "reviews#end_reviews", as: :end_reviews

  patch "places/:id", to: "places#update"

  post "/places/end_reviews", to: "places#end_reviews"

  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
end

app/controllers/routes_controller.rb
require "google/cloud/translate"
require 'open-uri'
require 'nokogiri'
require 'erb'

class RoutesController < ApplicationController
  before_action :set_route_params, only: [:index]
  before_action :set_origin_destination, only: [:index, :show]

  # share translate method with the view
  helper_method :translate

  def translate(text)
    api_key = ENV['GOOGLE_MAPS_API_KEY']
    translate_url = "https://translation.googleapis.com/language/translate/v2"

    response = Faraday.get(translate_url, {
      q: text,
      source: 'ja',
      target: 'en',
      key: api_key
    })

    json_response = JSON.parse(response.body)
    translated_text = json_response['data']['translations'].first['translatedText']
    translated_text
  rescue StandardError => e
    Rails.logger.error("Translation API error: #{e.message}")
    text # Return the original text if there's an error
  end

  def index
    puts ENV['RAPIDAPI_KEY'] # Output the API key in the terminal
    @navitime_routes = fetch_navitime_routes(session[:start_lat], session[:start_long], session[:end_lat], session[:end_long])

    if @navitime_routes
      # Initialize variables to store the best route characteristics
      quickest_route = shortest_route = less_walking_route = cheapest_route = nil

      @navitime_routes['items'].each do |route|
        route_time = route['summary']&.dig('move', 'time') || Float::INFINITY
        route_distance = route['summary']&.dig('move', 'distance') || Float::INFINITY
        route_walk_distance = route['summary']&.dig('move', 'walk_distance') || Float::INFINITY
        route_fare = route['summary']&.dig('move', 'fare', 'unit_0') || Float::INFINITY

        # Find the quickest route
        quickest_route = route if quickest_route.nil? || route_time < quickest_route['summary']['move']['time']

        # Find the shortest route
        shortest_route = route if shortest_route.nil? || route_distance < shortest_route['summary']['move']['distance']

        # Find the route with less walking
        less_walking_route = route if less_walking_route.nil? || route_walk_distance < less_walking_route['summary']['move']['walk_distance']

        # Find the cheapest route
        cheapest_route = route if cheapest_route.nil? || route_fare < cheapest_route['summary']['move']['fare']['unit_0']
      end
      # Set instance variables for use in the view
      @quickest_route = quickest_route
      @shortest_route = shortest_route
      @less_walking_route = less_walking_route
      @cheapest_route = cheapest_route
    end
  end

  def show
    route_no = params[:id]

    # Make a new API call using the same parameters in saved sessions
    navitime_routes = fetch_navitime_routes(session[:start_lat], session[:start_long], session[:end_lat], session[:end_long])

    @route = navitime_routes['items'].find { |r| r['summary']['no'] == route_no }

    Rails.logger.error(@route)

    if @route.nil?
      redirect_to routes_path, alert: "Route not found."
    else
      @sections = @route['sections']
    end

    # number of transport stops array
    # Assuming @route is already set and contains the necessary data
    @stops = []
    last_departure_number = nil

    @stops = []
    numbering_pairs = {}

    @route['sections'].each do |section|
      if section['numbering'].present?
        section['numbering'].each do |key, value|
          value.each do |numbering|
            symbol = numbering['symbol']
            number = numbering['number'].to_i

            # If we already have a stored number for this symbol, calculate the difference
            if numbering_pairs[symbol]
              difference = (numbering_pairs[symbol] - number).abs
              @stops << difference

              # After using the pair, reset the stored value to the current number
              numbering_pairs[symbol] = number
            else
              # Otherwise, store this number for future comparison
              numbering_pairs[symbol] = number
            end
          end
        end
      end
    end

    puts "!!stops: #{@stops}"

    @station_images = []
    @route['sections'].each_with_index do |section, index|
      station_name = translate(section['name'])
      if station_name.include?("3-chome")
        station_name.gsub!("3-chome", "sanchome")
      end
      station_name.gsub!(/\s*\([^)]+\)/, "")
      station_name.gsub!(" ", "-")
      if section['node_id'].present? && section['gateway'].nil?
        url = "https://www.tokyometro.jp/station/yardmap_img/figure_yardmap_#{station_name.downcase}_all.jpg"

        begin
        document = Nokogiri::HTML.parse(URI.open(url).read)
        unless document.search("h1").present?
          @station_images << {index: index, url: url}
        end
        rescue OpenURI::HTTPError => e
          Rails.logger.error("Error fetching station image: #{e.message}")
        end
      end
      if section['gateway'].present?
        place = Place.where("name ILIKE ?", "%#{station_name} Station%").first
        if place
          @station_images << {index: index, place: place}
        end
      end
    end
  end

  private

  def set_origin_destination
    @origin = session[:origin]
    @destination = session[:destination]
  end

  def set_route_params
    session[:start_lat] = params[:start_lat]
    session[:start_long] = params[:start_long]
    session[:end_lat] = params[:end_lat]
    session[:end_long] = params[:end_long]
    session[:origin] = params[:origin]
    session[:destination] = params[:destination]
  end

  def fetch_navitime_routes(start_lat, start_long, end_lat, end_long)
    datum = "wgs84"
    term = 1440
    limit = 5
    start_time = "2020-08-19T10:00:00"
    coord_unit = "degree"
    walk_route = "babycar"
    shape = true

    url = URI("https://navitime-route-totalnavi.p.rapidapi.com/route_transit?" +
      "start=#{start_lat}%2C#{start_long}&" +
      "goal=#{end_lat}%2C#{end_long}&" +
      "datum=#{datum}&" +
      "term=#{term}&" +
      "limit=#{limit}&" +
      "start_time=#{URI.encode_www_form_component(start_time)}&" +
      "coord_unit=#{coord_unit}&" +
      "walk_route=#{walk_route}&" +
      "shape=#{shape}")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-key"] = ENV['RAPIDAPI_KEY']
    request["x-rapidapi-host"] = 'navitime-route-totalnavi.p.rapidapi.com'

    response = http.request(request)

    if response.code == "200"
      JSON.parse(response.body)
    else
      Rails.logger.error("Navitime API request failed: #{response.body}")
      nil
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching Navitime routes: #{e.message}")
    nil
  end
end

app/views/routes/_routes.html.erb
<!-- app/views/routes/_route.html.erb -->
<div class="route-badges route card p-3 m-3 shadow-sm">
  <div class="d-flex justify-content-between mb-3">
    <h2>
      <!-- Badges for the route -->
      <% if route == @quickest_route %>
        <span class="badge badge-pill bg-success">Quickest Route</span>
      <% end %>
      <% if route == @shortest_route %>
        <span class="badge badge-pill short-color">Shortest Route</span>
      <% end %>
      <% if route == @less_walking_route %>
        <span class="badge badge-pill bg-warning">Less Walking</span>
      <% end %>
      <% if route == @cheapest_route %>
        <span class="badge badge-pill bg-info">Cheapest Route</span>
      <% end %>
      <!-- Display route number if no specific badge is applicable -->
      <% if ![route == @quickest_route, route == @shortest_route, route == @less_walking_route, route == @cheapest_route].any? %>
        <span class="badge badge-pill bg-light text-dark average-route">Average Route</span>
      <% end %>
    </h2>
    <%# top right corner for route score %>
    <!--<div>
      <i class="fa-solid fa-baby-carriage text-warning"></i>
      <%# <%= route.rating %>
      <p>(5) </p>
    </div>
    -->
  </div>
  <div class="routes-summary-bar">
    <ul class="stats-list">
      <li><i class="fa-solid fa-clock"> </i> <%= route['summary']&.dig('move', 'time') || 'N/A' %> min </li>
      <li><i class="fa-solid fa-location-pin"> </i> <%= route['summary']&.dig('move', 'distance') || 'N/A' %> m</li>
      <li><i class="fa-solid fa-person-walking"> </i> <%= route['summary']&.dig('move', 'walk_distance') || 'N/A' %> m</li>
      <li><i class="fa-solid fa-yen-sign"> </i> <%= route['summary']&.dig('move', 'fare', 'unit_0') || 'N/A' %></li>
    </ul>
    <% if route['summary']&.dig('no').present? %>
      <%= link_to "Go", route_path(route['summary']['no']), class: 'btn btn-primary' %>
    <% end %>
  </div>
  <% # Extract and list the transit stations %>
  <% stations = route['sections'].select { |section| section['node_types']&.include?('station') }.map { |station| station['name'] || 'Unknown' } %>
  <ul class="station-group">
    <li class="station-icon"><i class="fa-solid fa-train-subway"> </i>(<%= stations.size %>): </li>
    <% stations.each do |station| %>
      <% if stations.last == station %>
        <li class="station-list"> <%= translate(station) %> </li>
      <% else %>
        <li class="station-list"> <%= translate(station) %> </li>
        <i class="fa-solid fa-chevron-right" style="color:lightgray"> </i>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/routes/_section.html.erb
<!-- Include jQuery before Bootstrap -->
<%= javascript_include_tag 'https://code.jquery.com/jquery-3.5.1.min.js' %>
<!-- Modal structure for image preview -->
<!-- Your existing content -->
<% walk_card_index = 0 %> <!-- Initialize walk index once, outside of the loop -->
<% transport_card_index = 0 %> <!-- Initialize transport index once, outside of the loop -->
<% first_point_section = route['sections'].find { |s| s['type'] == 'point' && s['name'] == 'start' } %>
<% last_point_section = route['sections'].reverse.find { |s| s['type'] == 'point' && s['name'] == 'goal' } %>
<% place_ids = "" %> <!-- Initialize place_ids variable -->
<% route['sections'].each_with_index do |section, index| %> <!-- Loop over each section -->
  <div class="section mb-4">
    <% if section['type'] == 'point' %>
      <div class="card instruction-card card-point <%= "start-goal-card" if section == first_point_section || section == last_point_section %>"
          data-action="click->routes-map#handleCardClick"
        data-coordinates="<%= section['coord'].present? ? "#{section['coord']['lat']},#{section['coord']['lon']}" : '' %>"
        data-move="point">
        <p class="card-point-text">
          <% if section == first_point_section %>
            <i class="text-center fa-solid fa-location-dot text-success"></i> <span>Start</span> <%#= @origin %>
          <% elsif section == last_point_section %>
            <% place_ids += ",#{@destination}" %>
            <% if user_signed_in? %>
              <span><%= @destination %></span><%= link_to("End Trip", end_reviews_path(place_ids), class: "end-trip-btn") %>
            <% else %>
              <span><%= @destination %></span><%= link_to("End Trip", root_path, class: "end-trip-btn") %>
            <% end %>
          <% elsif section['node_id'].present? && section['gateway'].nil? %> <!-- condition: no gateway but has a node -->
            <div class="transfer-title-container">
              <% place_ids += ",#{translate(section['name'])} Station" %>
              <span class="transfer-station-text">
                <i class="fa-solid fa-right-left"> </i> <%= translate(section['name']) %> Sta.
              </span>
              <div class="transfer-card-img-icon-container">
                <% if @station_images.any? { |e| e[:index] == index} %>
                  <% url = @station_images.find { |e| e[:index] == index }[:url] %>
                <% else %>
                  <% url = "http://res.cloudinary.com/dckq0zged/image/upload/v1724436396/xqfdy2ahqffnbxooxkug.jpg" %>
                <% end %>
                <img class="transfer-card-img" id="imageTag-<%= index%>" src="<%= url %>" alt="elevator" data-action="click->routes-map#openImageModal">
                <p class="d-none" id="imageComment<%= index%>"><%= translate(section['name']) %></p>
                <div class="bottom-icons">
                  <img class="baby-changer-icon" src="http://res.cloudinary.com/dckq0zged/image/upload/v1724831678/z1gbt97pjssf2x5xcc40.png" alt="">
                  <img class="baby-changer-icon" src="http://res.cloudinary.com/dckq0zged/image/upload/v1724848852/taf1k3frhuuelqqxmniw.png" alt="">
                </div>
              </div>
            </div>
          <% else %>
            <% place_ids += ",#{translate(section['name'])} Station" %>
            <span class="point-title"><%= translate(section['name']) %> Sta.</span>
          <% end %>
          <% if section['gateway'].present? %>
            <div class="elevator-image-container">
              <% if @station_images.any? { |e| e[:index] == index} %>
                <% place = @station_images.find { |e| e[:index] == index }[:place] %>
                <% if place.photos.second %>
                  <%= image_tag url_for(place.photos.second), :data => { :action => "click->routes-map#openImageModal" }, :id => "imageTag-#{index}" %>
                  <p class="d-none" id="imageComment<%= index%>"><%= place.reviews.find { |r| r.photos.attached? }&.comment %></p>
                <% elsif place.photos.first %>
                  <%= image_tag url_for(place.photos.first), :data => { :action => "click->routes-map#openImageModal" }, :id => "imageTag-#{index}" %>
                  <p class="d-none" id="imageComment<%= index%>"><%= translate(section['name']) %></p>
                <% end %>
              <% else %>
                <img src="http://res.cloudinary.com/dckq0zged/image/upload/v1724434212/dnilq9ncpkzidf3ttuyc.png" alt="elevator" id= "imageTag-<%= index%>" data-action="click->routes-map#openImageModal">
                <p class="d-none" id="imageComment<%= index%>">Elevator</p>
              <% end %>
              <div class="exit">
                <i class="fa-solid fa-elevator"></i>
                <span class="exit-text"><%= translate(section['gateway']) %></span>
              </div>
            </div>
          <% end %>
        </p>
      </div>
    <% elsif section['type'] == 'move' %>
      <% if section['move'] == 'walk' %>
        <div class="card instruction-card card-walk"
        <% if section['distance'].to_i == 0 %>
          data-index=""
        <% else %>
          data-index="<%= walk_card_index %>"
          <% walk_card_index += 1 %>
        <% end %>
        data-action="click->routes-map#handleCardClick"
          data-move="walk">
          <div class="walk-stats-container">
            <ul class="walk-stats-list">
              <li><%= section['distance'] %>m</li>
              <li><%= section['time'] %> mins</li>
            </ul>
          </div>
          <i class="fa-solid fa-person-walking walk-icon"></i>
          <div class="card-walk-text">
            <span>Walk to <i class="arrow fa-solid fa-arrow-right"></i></span>
          </div>
        </div>
      <% else %>
        <% if section['transport'].present? %>
          <div class="card instruction-card card-transport" data-action="click->routes-map#handleCardClick"
            data-move="transport"
            data-index="<%= transport_card_index %>"> <!-- Use transport_card_index here -->
            <div class="card-transport-text">
              <span style="background-color:<%= section['transport']['color'] %>; color: #fff; padding: 0px 2px; border-radius: 3px;">
                <%= translate(section['transport']['name']) %>
              </span>
              <i class="fa-solid fa-train-subway " style="color:<%= section['transport']['color'] %>"></i>
              <div class="route-stop-container">
                <span class="route-stops" style="background-color:<%= section['transport']['color'] %> ">
                  <%= @stops[transport_card_index] %>
                  <!-- Display stop number -->
                </span>
                <p>Stops</p>
              </div>
            </div>
          </div>
          <% transport_card_index += 1 %> <!-- Increment transport index for each transport section -->
        <% else %>
          <p>Transport details not available for this step.</p>
        <% end %>
      <% end %>
    <% else %>
      <p>Unknown step in the journey. Please check the details.</p>
    <% end %>
  </div>
<% end %>

app/views/routes/create.html.erb
<h1>Routes#create</h1>
<p>Find me in app/views/routes/create.html.erb</p>

app/views/routes/destroy.html.erb
<h1>Routes#destroy</h1>
<p>Find me in app/views/routes/destroy.html.erb</p>

app/views/routes/index.html.erb
<!-- app/views/routes/index.html.erb -->
<div class="route-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://res.cloudinary.com/dckq0zged/image/upload/v1724468241/pnatl16tdbxjr9glkyr1.png);">
  <div class="container">
    <div class="route-start-stop">
      <button class="text-primary simple-back-button" onclick="window.history.back();">
        <i class="fa-solid fa-chevron-left"></i>
      </button>
      <h3 class="start"><i class="fa-solid fa-location-dot text-success"></i> <%= @origin %> </h3>
      <h3 class="stop"><i class="fa-solid fa-location-pin text-danger"></i> <%= @destination %></h3>
    </div>
  </div>
</div>
<% if @navitime_routes && @navitime_routes['items'].present? %>
  <% @navitime_routes['items'].each do |route| %>
    <%= render partial: 'routes', locals: { route: route } %>
  <% end %>
<% else %>
  <p>No routes available. </p>
<% end %>

app/views/routes/show.html.erb
<div id="imageModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageModalLabel">Elevator</h5>
      </div>
      <div class="modal-body text-center">
        <img id="modalImage" src="" alt="Image preview" style="max-width: 100%; height: auto;">
      </div>
    </div>
  </div>
</div>
<!-- frame -->
<div style="height:100vh;width:100vw;" data-controller="routes-map" data-route="<%= @route.to_json %>">
  <!--  -->
  <div class="d-none"><input id="input-fields" type="text"></div>
  <!-- map -->
  <div id="map" data-routes-map-target="map" style="z-index: 0; height: 60vh;" data-action="load@window->routes-map#initMap"></div>
  <!-- draggable-panel -->
  <div id="draggable-panel" class="bg-white w-100" data-controller="" style="height: 40vh;padding-top: 16px;">
    <div id="route-panel-content" class="w-100" data-routes-map-target="content">
      <!-- Panel content -->
      <div class="">
      </div>
      <!-- route metrics dashboard -->
      <div class="routes-summary-bar ps-1">
        <ul class="stats-list">
          <li><i class="fa-solid fa-clock"> </i> <%= @route['summary']&.dig('move', 'time') || 'N/A' %> min </li>
          <li><i class="fa-solid fa-location-pin"> </i> <%= @route['summary']&.dig('move', 'distance') || 'N/A' %> m</li>
          <li><i class="fa-solid fa-person-walking"> </i> <%= @route['summary']&.dig('move', 'walk_distance') || 'N/A' %> m</li>
          <li><i class="fa-solid fa-yen-sign"> </i> <%= @route['summary']&.dig('move', 'fare', 'unit_0') || 'N/A' %></li>
        </ul>
      </div>
      <div class="route-summary-trip">
        <p class="route-summary-trip-text">
          <span class="material-symbols-outlined text-success">
            location_on
          </span><span class="material-symbols-outlined">
            chevron_right
          </span>
          <% @route['sections'].each_with_index do |section, index| %>
            <% if section['type'] == 'move' && section['move'] == 'walk' %>
              <span class="material-symbols-outlined">directions_walk</span><span class="material-symbols-outlined">
                chevron_right
              </span>
            <% elsif section['type'] == 'move' && section['move'] == 'local_train' %>
              <span class="material-symbols-outlined"
                style="color:<%= section['transport']['color'] %>;">directions_subway</span><span class="material-symbols-outlined">
                chevron_right
              </span>
            <% elsif section['type'] == 'point' && section['node_id'].present? && section['gateway'].nil? %> <!-- This is for transfer points -->
              <span class="material-symbols-outlined">
                transfer_within_a_station
              </span><span class="material-symbols-outlined">
                chevron_right
              </span>
            <% end %>
          <% end %>
          <span class="material-symbols-outlined text-danger">
            flag
          </span>
        </p>
      </div>
      <% if @route.present? %>
        <div class="m-0 p-1 instructions-container">
          <!-- Render the partial that handles the route sections -->
          <%= render partial: 'section', locals: { route: @route } %>
        </div>
      <% else %>
        <p>No route details available.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/routes/update.html.erb
<h1>Routes#update</h1>
<p>Find me in app/views/routes/update.html.erb</p>